// @ts-check

import { expect, test } from "bun:test";
import * as ui from "../src/index.js";

test("exports exactly the frozen generic Omarchy UI API", () => {
  expect(Object.keys(ui).sort()).toEqual([
    "ActionBar",
    "AppShell",
    "BottomBar",
    "Button",
    "CenteredWorkspace",
    "EmptyState",
    "FieldRow",
    "FormField",
    "GlyphButton",
    "IconButton",
    "KeyHints",
    "Keycap",
    "Label",
    "ListRow",
    "MenuItem",
    "MenuSeparator",
    "MutedText",
    "PageColumn",
    "PanelHeader",
    "PopupSurface",
    "SectionLabel",
    "Separator",
    "StatusLine",
    "Surface",
    "Title",
    "TopBar",
    "alpha",
    "applyOmarchyRoles",
    "applyOmarchyStyle",
    "capSaturation",
    "formatColor",
    "mix",
    "omarchyBaseColors",
    "omarchyRoles",
    "omarchyStatusColors",
    "omarchyStyle",
    "omarchyTheme",
    "parseColor",
    "parseHyprlandColor",
    "parseShellToml",
    "resolveSurfaceColor",
    "role",
    "roles",
    "style",
  ]);

  expect(ui).not.toHaveProperty("actionButton");
  expect(ui).not.toHaveProperty("brandLockup");
  expect(ui).not.toHaveProperty("iconAsset");
  expect(ui).not.toHaveProperty("omarchyStyleFrom");
});

test("interactive and validation classes expose the exact reviewed builders", () => {
  expect(Object.getOwnPropertyNames(ui.Button.prototype).sort()).toEqual([
    "bordered",
    "build",
    "constructor",
    "danger",
    "disabled",
    "icon",
    "label",
    "loading",
    "loadingLabel",
    "onClick",
    "outlined",
    "selected",
    "size",
  ]);
  expect(Object.getOwnPropertyNames(ui.IconButton.prototype).sort()).toEqual([
    "bordered",
    "build",
    "constructor",
    "description",
    "disabled",
    "icon",
    "loading",
    "loadingLabel",
    "onClick",
    "outlined",
    "selected",
    "size",
  ]);
  expect(Object.getOwnPropertyNames(ui.GlyphButton.prototype).sort()).toEqual([
    "bordered",
    "build",
    "constructor",
    "description",
    "disabled",
    "glyph",
    "loading",
    "loadingLabel",
    "onClick",
    "outlined",
    "selected",
    "size",
  ]);
  expect(Object.getOwnPropertyNames(ui.MenuItem.prototype).sort()).toEqual([
    "build",
    "constructor",
    "danger",
    "detail",
    "disabled",
    "icon",
    "label",
    "onClick",
    "selected",
  ]);
  expect(Object.getOwnPropertyNames(ui.FormField.prototype).sort()).toEqual([
    "build",
    "constructor",
    "control",
    "error",
    "helper",
    "label",
  ]);
  expect(Object.getOwnPropertyNames(ui.ListRow.prototype).sort()).toEqual([
    "build",
    "child",
    "children",
    "constructor",
    "disabled",
    "onClick",
    "selected",
  ]);
  expect(Object.getOwnPropertyNames(ui.StatusLine.prototype).sort()).toEqual([
    "build",
    "constructor",
    "label",
    "loadingLabel",
    "state",
  ]);
});
